apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-simple-java-deployment
  labels:
    app: poc-simple-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-simple-java
  template:
    metadata:
      labels:
        app: poc-simple-java
    spec:
      containers:
      - name: poc-simple-java
        image: {{DOCKER_IMAGE}}
        ports:
        - containerPort: 8080
